---
title: "7 Wonders Duel"
author: "Harris Kingsley"
date: "2022-01-03"
output: html_document
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(googlesheets4)
library(extrafont)
library(tidyverse)
library(readxl)
library(patchwork)
library(ggpubr)
library(waffle)
library(magick)
duel_game <- read_sheet("https://docs.google.com/spreadsheets/d/1wC3KUIt7DSZ4vM8FKZFDmqa0BDT8uB1IbaCuIMnLzCI/edit?usp=sharing")
```
Inspired by a [reddit post](https://www.reddit.com/r/boardgames/comments/ru9ij9/patchwork_duel_data_viz/), I decided to see how my wife and I have been doing playing 7 Wonders Duel. Here is the original author's [code](https://github.com/emilynordmann/theaplotalypse) as well as [mine](https://github.com/hkingsley-code/blog/blob/main/content/post/2022-01-03-duel/index.Rmd). 


```{r,  echo=FALSE, warning= FALSE, message = FALSE }
# Set up colours for the graphs
duel_colours_2 <- c("#FF7433", "#3348FF")
```


```{r,  echo=FALSE, warning=FALSE, message=FALSE}
# Theme stuff
my_theme <- theme(plot.title = element_text(size=20, 
                                            family = "Verdana", 
                                            face = "bold", 
                                            hjust = 0.5),
                  plot.subtitle = element_text(size = 10, 
                                            family = "Verdana",
                                            hjust = 0.5),
                  axis.line = element_blank(), 
                  axis.ticks = element_blank(),
                  plot.background = element_rect("#E7E1DE"),
                  legend.background = element_rect("#E7E1DE"),
                  legend.text = element_text(family = "Verdana"),
                  panel.background = element_rect("#E7E1DE"),
                  legend.position = "bottom")
             
```


```{r,  echo=FALSE, warning=FALSE, message=FALSE}
# calculate percent wins for each player
overall_wins <- duel_game %>%
  group_by(WINNER) %>%
  count() %>%
  ungroup() %>%
  mutate(prop = n/sum(n),
         percent = prop * 100,
         ymax = cumsum(prop),
         ymin = c(0, head(ymax, n=-1)),
         labelPosition = (ymax + ymin) /2,
         label = paste0(WINNER, "\n ", round(percent,2), "%")) 
category_wins <- duel_game %>%
  group_by(WINNER, VICTORY_TYPE) %>%
  count() %>%
  ungroup() %>%
  mutate(prop = n/sum(n),
         percent = prop * 100,
         ymax = cumsum(prop),
         ymin = c(0, head(ymax, n=-1)),
         labelPosition = (ymax + ymin) /2,
         label = paste0(WINNER, "\n ", round(percent,2), "%")) 
```




```{r,  echo=FALSE, warning=FALSE, message=FALSE}
#Waffle plot - who wins Duel?
p1 <- duel_game %>%
  count(WINNER) %>%
  ggplot(aes(fill = WINNER, values = n)) +
  labs(title = "Winner", subtitle = "All categories", fill = NULL, colour = NULL,
       x = "Winner") +
  guides(fill = NULL, colour = NULL, x = NULL, y = NULL)  +
  geom_waffle(n_rows = 10, # number of rows
              size = .8, # thickness of tile line
              colour = "black", # colour of tile line
              flip = F, # controls if split left/right or up/down 
              radius = unit(4, "pt"), # adds gap between tiles
              show.legend = F,
              make_proportional = TRUE) +
  scale_fill_manual(values = duel_colours_2) + # add patchwork colours
  geom_label(family = "Verdana", 
             x=c(4, 9), 
             aes(y=5.5, 
                 label=overall_wins$label), 
            colour = c("black"), 
            show.legend = F,
            size = 4,
            fill = "white",
            label.padding = unit(.5, "lines"),
            label.r = unit(0.75, "lines"), #roundness of outer label line
            label.size = 1.5) + # thickness of outer label line
  theme_enhance_waffle() +
  my_theme
```


```{r, echo=FALSE, warning=FALSE, message = FALSE}
#Type of wins

#When a player wins, how do they win?


p2 <- duel_game %>%
  group_by(WINNER, VICTORY_TYPE) %>%
  count() %>%
  ungroup(VICTORY_TYPE) %>%
  mutate(prop = (n/sum(n))) %>%
  ggplot(aes(x = WINNER, y = prop, fill = VICTORY_TYPE)) +
  labs(title = "Winner", subtitle = "When a player wins, how do they win?", 
       x = NULL, 
       fill = NULL, colour = NULL, 
       y = NULL) +
  guides(fill = NULL, colour = NULL, x = NULL, y = NULL) +
  geom_col(colour = "black") +
  scale_fill_manual(values = c("#a6191c", "#006fa3", "#047b41")) +
  scale_y_continuous(labels = scales::percent) +
  my_theme
```



```{r, echo=FALSE, warning=FALSE, message = FALSE}
#Strategy - where does each player get their points from?

p3 <- duel_game %>%
  filter(VICTORY_TYPE == "Points") %>%
  pivot_longer(cols = `BLUE_C`:`TOTAL_H`, names_to = "type", values_to = "Points") %>%
  separate(col = "type", into = c("TYPE", "PLAYER"), sep = "_") %>%
  filter(WINNER == "Harris" & PLAYER == "H" |WINNER == "Charlotte" & PLAYER == "C") %>%
  group_by(WINNER, PLAYER, TYPE) %>%
  summarise(avg_points = mean(Points)) %>%
  ggplot(aes(x = reorder(TYPE, avg_points), y = avg_points, fill = PLAYER)) +
  geom_col(position = "dodge", colour = "black") +
  coord_flip() +
  labs(x = NULL, y = "Average points per game", title = "Winning Strategies",
       subtitle = "Where does each player get their points?") +
  scale_fill_manual(values = duel_colours_2, 
                    name = "Player", 
                    labels = c(c("Harris", "Charlotte"))) +
  my_theme
```




```{r, echo=FALSE, warning=FALSE, message=FALSE }
#Put it all together
logo <- image_read("duel-logo.jpg") # from magick
# stitch together plots using patchwork
p4 <- ggplot() +
  background_image(logo) + # from ggpubr
  labs(title = "7 Wonders Duel",
       subtitle = paste0("Games = ", nrow(duel_game))) +
  coord_fixed() +
  my_theme
p4 + p2 + p1 + p3 +
  plot_layout(ncol = 2, 
              nrow = 2, 
              widths = c(2,2),
              heights = c(4,8,4,8)) 
#ggsave(filename = "duel_full.png", width = 10, height = 10)
```